### ISSUE TITLE
missing dotnet_root, but it is installed

### ISSUE THREAD

**Issue by gshields** [tonybaloney/Pyjion#11]
dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

E:\PortableApps\src\py_src>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoftv.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

E:\PortableApps\src\py_src>python nbody.py
Can't find a .NET 5 installation in C:\Users\ghs\AppData\Local\Microsoft\dotnet, provide the DOTNET_ROOT environment variable if its installed somewhere unusual
.......................
os: windows 10 v20h
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40)

**Comment by tonybaloney** [comment]
Thanks for the info @gshields 

Could you share a couple of things to help diagnose this? I haven't yet figured out how to bundle the correct DLL in the wheel so its scanning the system at the moment.

The file its looking for is:

- `clrjit.dll`

Can you search for that inside `c:\\Program Files\\dotnet\\sdk` and paste the full path in this ticket?

**Comment by gshields** [comment]
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0

**Comment by tonybaloney** [comment]
Great. I've pushed a patch so that it'll pick up the right location.

**Comment by gshields** [comment]
new version not in pip
pip install pyjion
Requirement already satisfied: pyjion in
e:\portableapps\python39\lib\site-packages (0.0.2)
............................................................
Git is not public
git clone git@github.com:tonybaloney/pyjion --recurse-submodules
Cloning into 'pyjion'...
Warning: Permanently added the RSA host key for IP address '140.82.112.3'
to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
...............................
Download zip and
 python .\setup.py
Traceback (most recent call last):
  File "E:\PortableApps\src\Pyjion-master\Pyjion-master\setup.py", line 1,
in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'
..........................

Thanks for your help

**Comment by tonybaloney** [comment]
I hadn't released it yet :-)

Try now. its up on PyPi

**Comment by gshields** [comment]
It works!, Thanks, a bit slower than Cpython

$ time python ./nbody.py
-0.169075164
-0.169059907
0:09:01.281038 run time

real    9m1.529s
user    0m0.000s
sys     0m0.015s

Except I just found it created a file in the same folder names "祰楪湯氮杯"
size: 14.1 KB (14,502 bytes)
size on disk: 16.0 KB (16,384 bytes)

Looks like you have a bad pointer/dereference?

**Comment by gshields** [comment]
contents of strange file is :
JIT Compilation time report:
  Compiled 64 methods.
  Compiled 109091 bytecodes total (16532 max,  1704.55 avg).
  Time: total:      0.000 Mcycles/     0.000 ms
          max:      0.000 Mcycles/     0.000 ms
          avg:      0.000 Mcycles/     0.000 ms

  Total time by phases:
     PHASE                          inv/meth   Mcycles    time (ms)  % of
total    max (ms)

 ---------------------------------------------------------------------------------------
     Pre-import                       1.00        4.31       1.692
 inf%       0.186
     Importation                      1.00       21.84       8.576
 inf%       1.131
     Indirect call transform          1.00        0.02       0.008
 inf%       0.001
     Expand patchpoints               1.00        0.01       0.005
 inf%       0.000
     Post-import                      1.00        0.01       0.006
 inf%       0.000
     IBC instrumentation              0.00        0.00       0.000
-nan(ind)%       0.000
     Morph - Init                     1.00        0.20       0.077
 inf%       0.013
     Morph - Inlining                 1.00        2.54       0.996
 inf%       0.190
     Morph - Add internal blocks      1.00        0.09       0.036
 inf%       0.005
     Allocate Objects                 1.00        0.03       0.011
 inf%       0.003
     Remove empty try                 1.00        0.02       0.008
 inf%       0.002
     Remove empty finally             1.00        0.01       0.005
 inf%       0.000
     Merge callfinally chains         1.00        0.01       0.005
 inf%       0.000
     Clone finally                    1.00        0.02       0.007
 inf%       0.002
     Update finally target flags      0.00        0.00       0.000
-nan(ind)%       0.000
     Compute preds                    1.00        0.44       0.173
 inf%       0.024
     Update flow graph early pass     1.00        0.34       0.134
 inf%       0.017
     Morph - Structs/AddrExp          1.00        3.98       1.563
 inf%       0.188
     Morph - ByRefs                   1.00        0.02       0.010
 inf%       0.002
     Morph - Promote Structs          1.00        0.09       0.037
 inf%       0.006
     Morph - Global                   1.00       17.46       6.857
 inf%       0.800
     Morph - Finish                   0.00        0.00       0.000
-nan(ind)%       0.000
     GS Cookie                        1.00        2.87       1.128
 inf%       0.312
     Mark GC poll blocks              1.00        0.08       0.031
 inf%       0.005
     Compute edge weights (1, false)   1.00        0.47       0.183
 inf%       0.018
     Create EH funclets               1.00        0.06       0.024
 inf%       0.003
     Merge throw blocks               1.00        0.02       0.009
 inf%       0.000
     Optimize layout                  1.00        3.63       1.425
 inf%       0.666
     Compute blocks reachability      1.00        2.92       1.148
 inf%       0.255
     Redundant zero Inits             1.00        0.24       0.094
 inf%       0.007
     Optimize loops                   1.00        0.82       0.320
 inf%       0.111
     Clone loops                      1.00        0.04       0.015
 inf%       0.002
     Unroll loops                     1.00        0.02       0.008
 inf%       0.002
     Hoist loop code                  1.00        0.08       0.032
 inf%       0.006
     Mark local vars                  1.00        3.65       1.433
 inf%       0.170
     Optimize bools                   1.00        0.08       0.032
 inf%       0.004
     Find oper order                  1.00        2.88       1.132
 inf%       0.137
     Set block order                  1.00        1.84       0.724
 inf%       0.092
     Build SSA representation         0.00        9.65       3.789
 inf%       0.844
       SSA: topological sort            1.00        0.73       0.286
 inf%       0.037
       SSA: Doms1                       1.00        1.20       0.471
 inf%       0.129
       SSA: liveness                    1.00        0.01       0.003
 inf%       0.000
       SSA: DF                          1.00        1.76       0.692
 inf%       0.221
       SSA: insert phis                 1.00        1.23       0.481
 inf%       0.087
       SSA: rename                      1.00        4.73       1.856
 inf%       0.370
     Early Value Propagation          1.00        0.04       0.014
 inf%       0.001
     Do value numbering               1.00       13.97       5.486
 inf%       0.755
     Optimize index checks            1.00        1.25       0.489
 inf%       0.073
     Optimize Valnum CSEs             2.00        2.47       0.968
 inf%       0.290
     VN based copy prop               1.00       30.89      12.129
 inf%       4.017
     Assertion prop                   1.00       18.39       7.221
 inf%       2.095
     Update flow graph opt pass       0.02        0.13       0.050
 inf%       0.050
     Compute edge weights (2, false)   0.02        0.04       0.015
 inf%       0.015
     Insert GC Polls                  1.00        0.03       0.012
 inf%       0.002
     Determine first cold block       1.00        0.01       0.005
 inf%       0.000
     Rationalize IR                   1.00        4.32       1.695
 inf%       0.230
     Do 'simple' lowering             1.00        0.97       0.382
 inf%       0.056
     Local var liveness               0.00       30.96      12.158
 inf%       2.051
       Local var liveness init          2.06       11.07       4.349
 inf%       0.592
       Per block local var liveness     2.86       13.03       5.117
 inf%       0.936
       Global local var liveness        2.06        6.86       2.692
 inf%       0.523
     Lowering decomposition           0.00        0.00       0.000
-nan(ind)%       0.000
     Lowering nodeinfo                1.00        1.55       0.609
 inf%       0.096
     Calculate stack level slots      1.00        0.93       0.365
 inf%       0.062
     Linear scan register alloc       0.00       38.21      15.006
 inf%       2.843
       LSRA build intervals             1.00       17.50       6.873
 inf%       1.122
       LSRA allocate                    1.00       15.67       6.153
 inf%       1.206
       LSRA resolve                     1.00        5.04       1.980
 inf%       0.515
     Generate code                    1.00       15.20       5.968
 inf%       1.058
     Emit code                        1.00        3.97       1.558
 inf%       0.239
     Emit GC+EH tables                1.00        0.88       0.346
 inf%       0.033
     Post-Emit                        0.00        0.00       0.000
-nan(ind)%       0.000

  'End phase slop' should be very small (if not, there's unattributed
time):     0.035 Mcycles = inf% of total.


JIT Compilation time report:
  Compiled 60 methods.
  Compiled 107403 bytecodes total (16532 max,  1790.05 avg).
  Time: total:      0.000 Mcycles/     0.000 ms
          max:      0.000 Mcycles/     0.000 ms
          avg:      0.000 Mcycles/     0.000 ms

  Total time by phases:
     PHASE                          inv/meth   Mcycles    time (ms)  % of
total    max (ms)

 ---------------------------------------------------------------------------------------
     Pre-import                       1.00        4.97       1.918
 inf%       0.213
     Importation                      1.00       21.79       8.412
 inf%       1.239
     Indirect call transform          1.00        0.02       0.006
 inf%       0.000
     Expand patchpoints               1.00        0.01       0.005
 inf%       0.000
     Post-import                      1.00        0.01       0.005
 inf%       0.000
     IBC instrumentation              0.00        0.00       0.000
-nan(ind)%       0.000
     Morph - Init                     1.00        0.17       0.066
 inf%       0.007
     Morph - Inlining                 1.00        2.25       0.869
 inf%       0.132
     Morph - Add internal blocks      1.00        0.09       0.035
 inf%       0.005
     Allocate Objects                 1.00        0.02       0.009
 inf%       0.002
     Remove empty try                 1.00        0.02       0.006
 inf%       0.001
     Remove empty finally             1.00        0.01       0.005
 inf%       0.000
     Merge callfinally chains         1.00        0.01       0.005
 inf%       0.000
     Clone finally                    1.00        0.02       0.006
 inf%       0.001
     Update finally target flags      0.00        0.00       0.000
-nan(ind)%       0.000
     Compute preds                    1.00        0.45       0.173
 inf%       0.027
     Update flow graph early pass     1.00        0.31       0.121
 inf%       0.017
     Morph - Structs/AddrExp          1.00        3.73       1.439
 inf%       0.185
     Morph - ByRefs                   1.00        0.02       0.008
 inf%       0.001
     Morph - Promote Structs          1.00        0.08       0.031
 inf%       0.002
     Morph - Global                   1.00       17.08       6.593
 inf%       0.789
     Morph - Finish                   0.00        0.00       0.000
-nan(ind)%       0.000
     GS Cookie                        1.00        2.69       1.040
 inf%       0.334
     Mark GC poll blocks              1.00        0.10       0.039
 inf%       0.011
     Compute edge weights (1, false)   1.00        0.44       0.172
 inf%       0.017
     Create EH funclets               1.00        0.05       0.019
 inf%       0.002
     Merge throw blocks               1.00        0.02       0.008
 inf%       0.000
     Optimize layout                  1.00        3.49       1.348
 inf%       0.604
     Compute blocks reachability      1.00        2.78       1.072
 inf%       0.223
     Redundant zero Inits             1.00        0.25       0.096
 inf%       0.004
     Optimize loops                   1.00        0.82       0.317
 inf%       0.108
     Clone loops                      1.00        0.03       0.013
 inf%       0.002
     Unroll loops                     1.00        0.02       0.007
 inf%       0.001
     Hoist loop code                  1.00        0.08       0.032
 inf%       0.007
     Mark local vars                  1.00        3.59       1.387
 inf%       0.166
     Optimize bools                   1.00        0.08       0.030
 inf%       0.004
     Find oper order                  1.00        2.86       1.106
 inf%       0.129
     Set block order                  1.00        1.81       0.698
 inf%       0.091
     Build SSA representation         0.00        9.43       3.638
 inf%       0.607
       SSA: topological sort            1.00        1.25       0.481
 inf%       0.207
       SSA: Doms1                       1.00        1.11       0.428
 inf%       0.092
       SSA: liveness                    1.00        0.01       0.002
 inf%       0.000
       SSA: DF                          1.00        1.53       0.591
 inf%       0.153
       SSA: insert phis                 1.00        1.13       0.436
 inf%       0.065
       SSA: rename                      1.00        4.40       1.699
 inf%       0.258
     Early Value Propagation          1.00        0.04       0.014
 inf%       0.001
     Do value numbering               1.00       13.31       5.137
 inf%       0.674
     Optimize index checks            1.00        1.40       0.540
 inf%       0.083
     Optimize Valnum CSEs             2.00        2.00       0.773
 inf%       0.097
     VN based copy prop               1.00       28.55      11.018
 inf%       3.141
     Assertion prop                   1.00       16.60       6.406
 inf%       1.389
     Update flow graph opt pass       0.02        0.12       0.047
 inf%       0.047
     Compute edge weights (2, false)   0.02        0.04       0.014
 inf%       0.014
     Insert GC Polls                  1.00        0.03       0.012
 inf%       0.002
     Determine first cold block       1.00        0.01       0.005
 inf%       0.000
     Rationalize IR                   1.00        4.28       1.653
 inf%       0.218
     Do 'simple' lowering             1.00        0.95       0.369
 inf%       0.053
     Local var liveness               0.00       30.37      11.722
 inf%       1.911
       Local var liveness init          2.07       10.69       4.126
 inf%       0.567
       Per block local var liveness     2.88       12.91       4.985
 inf%       0.891
       Global local var liveness        2.07        6.77       2.612
 inf%       0.453
     Lowering decomposition           0.00        0.00       0.000
-nan(ind)%       0.000
     Lowering nodeinfo                1.00        1.49       0.576
 inf%       0.088
     Calculate stack level slots      1.00        0.90       0.349
 inf%       0.058
     Linear scan register alloc       0.00       37.22      14.368
 inf%       2.661
       LSRA build intervals             1.00       17.22       6.647
 inf%       1.037
       LSRA allocate                    1.00       15.20       5.867
 inf%       1.143
       LSRA resolve                     1.00        4.80       1.854
 inf%       0.482
     Generate code                    1.00       14.75       5.694
 inf%       1.075
     Emit code                        1.00        4.10       1.582
 inf%       0.254
     Emit GC+EH tables                1.00        0.83       0.321
 inf%       0.031
     Post-Emit                        0.00        0.00       0.000
-nan(ind)%       0.000

  'End phase slop' should be very small (if not, there's unattributed
time):     0.035 Mcycles = inf% of total.

**Comment by tonybaloney** [comment]
Cool! I wouldn't expect it to be faster (yet).

I stripped out all the original optimisations in order to get the core platform stable.

Its calling the same C-API functions for pretty much every opcodes, only a few opcodes would be slightly quicker. 
Also there are some exception handling scenarios which it doesn't support, so the overhead of the JIT failing and bouncing back to the CPython evaluation loop would slow it down.

Can you share a copy of `nbody.py` onto this thread?

That file looks like the analytics drop for .NET CLR JIT engine, so I've probably given it a filename with some bad encoding. somewhere

**Comment by tonybaloney** [comment]
I'll close this one and track the file bug under https://github.com/tonybaloney/Pyjion/issues/15

**Comment by gshields** [comment]
#import pyjion
#pyjion.enable()

import sys
from time import strftime, localtime
from datetime import datetime

def combinations(l):
    result = []
    for x in range(len(l) - 1):
        ls = l[x+1:]
        for y in ls:
            result.append((l[x],y))
    return result

PI = 3.14159265358979323
SOLAR_MASS = 4 * PI * PI
DAYS_PER_YEAR = 365.24

BODIES = {
    'sun': ([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], SOLAR_MASS),

    'jupiter': ([4.84143144246472090e+00,
                 -1.16032004402742839e+00,
                 -1.03622044471123109e-01],
                [1.66007664274403694e-03 * DAYS_PER_YEAR,
                 7.69901118419740425e-03 * DAYS_PER_YEAR,
                 -6.90460016972063023e-05 * DAYS_PER_YEAR],
                9.54791938424326609e-04 * SOLAR_MASS),

    'saturn': ([8.34336671824457987e+00,
                4.12479856412430479e+00,
                -4.03523417114321381e-01],
               [-2.76742510726862411e-03 * DAYS_PER_YEAR,
                4.99852801234917238e-03 * DAYS_PER_YEAR,
                2.30417297573763929e-05 * DAYS_PER_YEAR],
               2.85885980666130812e-04 * SOLAR_MASS),

    'uranus': ([1.28943695621391310e+01,
                -1.51111514016986312e+01,
                -2.23307578892655734e-01],
               [2.96460137564761618e-03 * DAYS_PER_YEAR,
                2.37847173959480950e-03 * DAYS_PER_YEAR,
                -2.96589568540237556e-05 * DAYS_PER_YEAR],
               4.36624404335156298e-05 * SOLAR_MASS),

    'neptune': ([1.53796971148509165e+01,
                 -2.59193146099879641e+01,
                 1.79258772950371181e-01],
                [2.68067772490389322e-03 * DAYS_PER_YEAR,
                 1.62824170038242295e-03 * DAYS_PER_YEAR,
                 -9.51592254519715870e-05 * DAYS_PER_YEAR],
                5.15138902046611451e-05 * SOLAR_MASS) }


SYSTEM = list(BODIES.values())
PAIRS = combinations(SYSTEM)


def advance(dt, n, bodies=SYSTEM, pairs=PAIRS):

    for i in range(n):
        for (([x1, y1, z1], v1, m1),
             ([x2, y2, z2], v2, m2)) in pairs:
            dx = x1 - x2
            dy = y1 - y2
            dz = z1 - z2
            mag = dt * ((dx * dx + dy * dy + dz * dz) ** (-1.5))
            b1m = m1 * mag
            b2m = m2 * mag
            v1[0] -= dx * b2m
            v1[1] -= dy * b2m
            v1[2] -= dz * b2m
            v2[0] += dx * b1m
            v2[1] += dy * b1m
            v2[2] += dz * b1m
        for (r, [vx, vy, vz], m) in bodies:
            r[0] += dt * vx
            r[1] += dt * vy
            r[2] += dt * vz


def report_energy(bodies=SYSTEM, pairs=PAIRS, e=0.0):

    for (((x1, y1, z1), v1, m1),
         ((x2, y2, z2), v2, m2)) in pairs:
        dx = x1 - x2
        dy = y1 - y2
        dz = z1 - z2
        e -= (m1 * m2) / ((dx * dx + dy * dy + dz * dz) ** 0.5)
    for (r, [vx, vy, vz], m) in bodies:
        e += m * (vx * vx + vy * vy + vz * vz) / 2.
    print("%.9f" % e)

def offset_momentum(ref, bodies=SYSTEM, px=0.0, py=0.0, pz=0.0):

    for (r, [vx, vy, vz], m) in bodies:
        px -= vx * m
        py -= vy * m
        pz -= vz * m
    (r, v, m) = ref
    v[0] = px / m
    v[1] = py / m
    v[2] = pz / m

def main(n, ref='sun'):
    offset_momentum(BODIES[ref])
    report_energy()
    advance(0.01, n)
    report_energy()

def cur_time():
  tmp = strftime('%a, %d %b %Y %H:%M:%S', localtime())
  print(tmp)

if __name__ == '__main__':
    start_time = datetime.now()
    #main(int(sys.argv[1]))
    main(50000000)
    print (datetime.now() - start_time, 'run time')
#ipy -OO nbody.py 50000000
