### ISSUE TITLE
Manage object reference counting via RAII

### ISSUE THREAD

**Issue by tetsuo-cpp** [tonybaloney/Pyjion#123]
I noticed that in `intrins.cpp`, there's quite a bit of code that manually calls `Py_INCREF` and `Py_DECREF` when references to a `PyObject` go in and out of scope. 

I'm thinking that it might be easier to avoid reference leaks if this code uses RAII to cleanup where applicable. So we could have a wrapper type called something like `PyObjectRef` that increments/decrements the ref count with its constructor and destructor (and maybe one specifically for tuples).

Apologies if you've already considered this. It came to mind when I was reading through the code so I figured I'd bring it up.

**Comment by tonybaloney** [comment]
There's already an RAII wrapper in `util.h` called `py_ptr` but its only really used for the unit tests

You've probably noticed already the bugs related to reference leaks and container types. 

There are some other considerations here:

* Some of the CPython C-API uses borrowed references, some use new references
* Some of the reference counting effect of OPCODEs is implied. e.g. LOAD_NAME implies an increment of the object and CALL_FUNCTION implies a decrement of that same variable. 
* The code goes between Pyjion and CPython's EvalFrameDefault (the normal CPython frame loop). IF there's a bit of code that Pyjion doesn't support, like the yield operator, it defaults back to EvalFrameDefault. Therefore the reference count of the objects should be the same
* CPython's ceval loop uses a _lot_ of borrowed references

RAII could help with the PyJit_ functions in `intrins.cpp` as you've noticed, but I don't know if its that simple

**Comment by tetsuo-cpp** [comment]
Understood, sounds like it might not be practical to do this. I'll just close this for now.
