### ISSUE TITLE
Implement PEP590 vector call in MethCallN

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/Pyjion#24]
Existing method `MethCallN` will use traditional `pyobject_call` for method calls with more than 4 args (inc. self).

See `Call<T>` for inspiration on how this could be implemented.

```cpp
PyObject* MethCallN(PyObject* self, PyMethodLocation* method_info, PyObject* args) {
    PyObject* res;
    if(!PyTuple_Check(args)) {
        PyErr_Format(PyExc_TypeError,
                     "invalid arguments for method call");
        Py_DECREF(args);
        delete method_info;
        return nullptr;
    }
    // TODO : Support vector arg calls.
    if (method_info->object != nullptr)
    {
        auto target = method_info->method;
        auto obj =  method_info->object;
        auto args_tuple = PyTuple_New(PyTuple_Size(args) + 1);
#ifdef DUMP_TRACES
        fprintf(g_traceLog, "Tuple <%lu> at %p (MethCallN)\n", PyTuple_Size(args) + 1, args_tuple);
#endif
        PyTuple_SetItem(args_tuple, 0, obj);
        for (int i = 0 ; i < PyTuple_Size(args) ; i ++){
            PyTuple_SetItem(args_tuple, i+1, PyTuple_GetItem(args, i));
        }
#ifdef GIL
        PyGILState_STATE gstate;
        gstate = PyGILState_Ensure();
#endif
        res = PyObject_Call(target, args_tuple, nullptr);
#ifdef GIL
        PyGILState_Release(gstate);
#endif
        if (res == nullptr){
            Py_DECREF(args_tuple);
            Py_DECREF(args);
            Py_XDECREF(target);
            Py_DECREF(obj);
            delete method_info;
            return nullptr;
        }
        Py_DECREF(args_tuple);
        Py_DECREF(args);
        Py_DECREF(target);
        Py_DECREF(obj);
        delete method_info;
        return res;
    }
    else {
        auto target = method_info->method;
#ifdef GIL
        PyGILState_STATE gstate;
        gstate = PyGILState_Ensure();
#endif
        res = PyObject_Call(target, args, nullptr);
#ifdef GIL
        PyGILState_Release(gstate);
#endif
        if (res == nullptr){
            Py_DECREF(args);
            Py_DECREF(target);
            delete method_info;
            return nullptr;
        }
        Py_DECREF(args);
        Py_DECREF(target);
        delete method_info;
        return res;
    }
}
```

**Comment by tetsuo-cpp** [comment]
I started having a look at this code recently.

> Existing method MethCallN will use traditional pyobject_call for method calls with more than 4 args (inc. self).

Isn't it 10 args (not 4)? From my reading, the `MethCall[0-10]` functions use `Call<T>` under the hood which uses the vector call. But the `MethCallN` function which gets used when there are more than 10 args, doesn't use it. So this issue is about modifying `MethCallN` to use this API.

**Comment by tonybaloney** [comment]
> I started having a look at this code recently.
> 
> > Existing method MethCallN will use traditional pyobject_call for method calls with more than 4 args (inc. self).
> 
> Isn't it 10 args (not 4)? From my reading, the `MethCall[0-10]` functions use `Call<T>` under the hood which uses the vector call. But the `MethCallN` function which gets used when there are more than 10 args, doesn't use it. So this issue is about modifying `MethCallN` to use this API.

Correct. It was 4 when I wrote this issue but I extended that to 10 using a template function

> 
> Just wanted to check that I'm understanding the code properly.
> 
> Edit: Actually, now I'm not sure I understand this. It seems like it's already using the vector args API for anything less than 10 args and then falling back to the traditional call for 11+ args. This seems to be exactly how non-method calls (`Call[0-10]` vs `CallN`) work at the moment.

Function calls and method calls are very similar, they both have a call target but method calls also have an extra argument for self.
For anything beyond 10, the JIT will roll up the arguments into a tuple (`args` argument). There are then two ways to call functions in the CPython C-API. Using `PyObject_Call`, which takes a tuple, or `PyObject_VectorCall`, which takes a vector (a tightly packed array).
For the template functions, this is easy to do, because it uses arg unpacking. For the "N" you'd have to do this in a list.

**Comment by tonybaloney** [comment]
@tetsuo-cpp you wanna take this issue on?

**Comment by tetsuo-cpp** [comment]
> @tetsuo-cpp you wanna take this issue on?

Yes please.

> For anything beyond 10, the JIT will roll up the arguments into a tuple (args argument). There are then two ways to call functions in the CPython C-API. Using PyObject_Call, which takes a tuple, or PyObject_VectorCall, which takes a vector (a tightly packed array).

Understood. So currently Pyjion creates a tuple and uses `PyObject_Call` for anything with >= 10 args. But we want to change it to use `PyObject_VectorCall` even in that case?

Also, do we want to make the equivalent change to regular function calls? I see that it also builds an intermediary tuple for anything with more than 10 args.

**Comment by tonybaloney** [comment]
Yes that's correct, but only if it supports PEP590 (see the other methods for the correct PyCFunction check)
