### ISSUE TITLE
Python crash running pyparsing unit tests

### ISSUE THREAD

**Issue by ptmcg** [tonybaloney/Pyjion#357]
See attached test log.

Pyparsing tests can be found at pyparsing/pyparsing GitHub repo.  See pyjion_testing branch to run unittests with pyjion enabled.
[pyparsing_test_fail_pyjion.txt](https://github.com/tonybaloney/Pyjion/files/6936786/pyparsing_test_fail_pyjion.txt)

**Comment by tonybaloney** [comment]
Tried this on 1.1.1 by adding 

```python
    def setUp(self):
        pyjion.enable()
    
    def tearDown(self):
        pyjion.disable()
``` 

To the `TestCase` class in `test_unit.py`. The tests run. There are a handful of failures, not sure if they're related to pyjion

**Comment by tonybaloney** [comment]
So the initial crash is fixed :-)

**Comment by ptmcg** [comment]
Thanks - I'll update that branch with latest pyparsing updates and tests and rerun with pyjion.
