### ISSUE TITLE
ModuleNotFoundError using PyCharm

### ISSUE THREAD

**Issue by JustinBacher** [tonybaloney/Pyjion#417]
I downloaded and installed .NET 5 Runtime, and then installed Pyjion using PyCharm. Ran my code with `import pyjion; pyjion.enable()` in the imports and got this error:

```
Traceback (most recent call last):
  File "D:\Python Workspaces\Lyn\test.py", line 4, in <module>
    import pyjion
  File "D:\Python Workspaces\Lyn\venv\lib\site-packages\pyjion\__init__.py", line 70, in <module>
    from ._pyjion import *  # NOQA
ModuleNotFoundError: No module named 'pyjion._pyjion'
```

So then I saw [this issue](https://github.com/tonybaloney/Pyjion/issues/93) and noticed it's recommended to use a virtual environment and tried using venv in PyCharm and it still shows the same error. Tried searching for others that had this same issue and I feel I'm alone. Hope I'm not!

**Comment by tonybaloney** [comment]
hi, thanks for the report. Which version of Python are you using and which version of Pyjion did it install?

This error means that it failed to compile the Pyjion extension (I've since improved the error message)

**Comment by JustinBacher** [comment]
Sorry, I guess I should have stated my environment. 

- Python 3.10
- Pyjion 0.15.0
- Windows 11 *(if that really means anything)*

**Comment by JustinBacher** [comment]
Sorry, I specified the version in PyCharm, *(don't know why it didn't use the latest release)* it worked though! Told me to download/install .NET 6 and it's working fine now! Thanks for your help and sorry for the trouble.
