### ISSUE TITLE
Linux Development Support

### ISSUE THREAD

**Issue by elkd** [tonybaloney/Pyjion#421]
Hi, Anthon

I am wondering if it is an okay idea to remove Visual Studio from the required tools for development? I'm trying to build from source on my Ubuntu machine, so far it looks okay  (a few issues with CMake and skbuild). 

Dotnet 6 rc can be pulled easily on Linux machines. Contribution md was written in 2016 but I also see you're maintaining a fork of skbuild for VS support. So yeah maybe VS can be just a recommendation instead of a requirement?

**Comment by tonybaloney** [comment]
Hi,

Visual Studio isn't required for development, where did you see that? I'll update the docs.

**Comment by tonybaloney** [comment]
Ah I just noticed the `CONTRIBUTING.md` file. All of that information was wrong so I've deleted the file. 

If you open this project in VS Code on a Linux machine, it'll prompt you to use the DevContainer, which has all the dependencies required. 

This is the current development/contributing guide https://pyjion.readthedocs.io/en/latest/development.html

**Comment by elkd** [comment]
Ok, thanks I got it. Let me also try to use VSCode. CMake below 3.13 has no add_link_options, see [here](https://cmake.org/cmake/help/latest/command/add_link_options.html). I can update the development docs so in case someone doesn't use the devcontainer, they shouldn't use CMake from the package manager (it's usually an old version).
