### ISSUE TITLE
Toy program benchmarks

### ISSUE THREAD

**Issue by hanabi1224** [tonybaloney/Pyjion#445]
Hi there, 
Pyjion is quite an interesting project and the idea of making it a drop-in replacement for CPython with JIT + full C extension compatibilities is hilarious!

Out of curiosity, I run some of the toy benchmark programs from [benchmarksgame](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html) to compare CPython 3.10,  pypy 3.7 and Pyjion, however, the result shows Pyjion is (at this moment) still much slower than the other 2 (with the same source code), which is different from [microbenchmark results](https://www.trypyjion.com/#benchmarks). I understand toy program is a very different scenario from microbenchmarks, just curious if there's plan to optimize performance for that scenario and what is the goal. Thanks!

BTW, I published my result [here](https://programming-language-benchmarks.vercel.app/python) for your reference. It runs on GH action VM with 2 core Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz

**Comment by tonybaloney** [comment]
Which did you run? Many of the benchmarks are in the benchmark suite, you can see the results in GitHub actions or run them locally. Yes, a few are slower, but most are faster fannkuch, n-body, n-queens are all faster.

**Comment by hanabi1224** [comment]
Here's the result of my local run of nbody program, and I can repro the same result on GH action VM.  I was injecting below 2 lines to the top of the script to enable pyjion, 
```python
import pyjion
pyjion.enable()
```

not sure what I was doing wrong except not using a microbenchmark framework, but the result obviously disagrees with that from [microbenchmark](https://github.com/tonybaloney/Pyjion/runs/4258757216?check_suite_focus=true#step:7:82) (even locally on my computer)

![image](https://user-images.githubusercontent.com/6546635/142632374-cb94c216-c433-4a4c-a7ae-6df090ac4f75.png)


Update: I dig into it a little bit, and found the very first run (by setting repeat=1 and number=1) is actually slower which is consistent with my result.  I think the current microbenchmark is more reflecting scenarios in which scripts are long-running, like web servers, but for one-shot scripts, it does not reflect the fact that it slows down the program by a lot, and pypy3 is doing better (at this moment) for the one-shot scenarios. So my question is, what is the plan for optimizing one-shot scenarios


![image](https://user-images.githubusercontent.com/6546635/142628059-917cc25e-6d22-488b-b4fa-646af8e54e4c.png)

![image](https://user-images.githubusercontent.com/6546635/142628348-96e2ecec-c134-4b13-8fff-846b3b89bc60.png)


```python
# The Computer Language Benchmarks Game
# https://salsa.debian.org/benchmarksgame-team/benchmarksgame/
#
# originally by Kevin Carson
# modified by Tupteq, Fredrik Johansson, and Daniel Nanz
# modified by Maciej Fijalkowski
# 2to3

# comment out these 2 lines to disable pyjion
import pyjion
pyjion.enable()

import sys


def combinations(l):
    result = []
    for x in range(len(l) - 1):
        ls = l[x+1:]
        for y in ls:
            result.append((l[x], y))
    return result


PI = 3.14159265358979323
SOLAR_MASS = 4 * PI * PI
DAYS_PER_YEAR = 365.24

BODIES = {
    'sun': ([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], SOLAR_MASS),

    'jupiter': ([4.84143144246472090e+00,
                 -1.16032004402742839e+00,
                 -1.03622044471123109e-01],
                [1.66007664274403694e-03 * DAYS_PER_YEAR,
                 7.69901118419740425e-03 * DAYS_PER_YEAR,
                 -6.90460016972063023e-05 * DAYS_PER_YEAR],
                9.54791938424326609e-04 * SOLAR_MASS),

    'saturn': ([8.34336671824457987e+00,
                4.12479856412430479e+00,
                -4.03523417114321381e-01],
               [-2.76742510726862411e-03 * DAYS_PER_YEAR,
                4.99852801234917238e-03 * DAYS_PER_YEAR,
                2.30417297573763929e-05 * DAYS_PER_YEAR],
               2.85885980666130812e-04 * SOLAR_MASS),

    'uranus': ([1.28943695621391310e+01,
                -1.51111514016986312e+01,
                -2.23307578892655734e-01],
               [2.96460137564761618e-03 * DAYS_PER_YEAR,
                2.37847173959480950e-03 * DAYS_PER_YEAR,
                -2.96589568540237556e-05 * DAYS_PER_YEAR],
               4.36624404335156298e-05 * SOLAR_MASS),

    'neptune': ([1.53796971148509165e+01,
                 -2.59193146099879641e+01,
                 1.79258772950371181e-01],
                [2.68067772490389322e-03 * DAYS_PER_YEAR,
                 1.62824170038242295e-03 * DAYS_PER_YEAR,
                 -9.51592254519715870e-05 * DAYS_PER_YEAR],
                5.15138902046611451e-05 * SOLAR_MASS)}


SYSTEM = list(BODIES.values())
PAIRS = combinations(SYSTEM)


def advance(dt, n, bodies=SYSTEM, pairs=PAIRS):

    for i in range(n):
        for (([x1, y1, z1], v1, m1),
             ([x2, y2, z2], v2, m2)) in pairs:
            dx = x1 - x2
            dy = y1 - y2
            dz = z1 - z2
            mag = dt * ((dx * dx + dy * dy + dz * dz) ** (-1.5))
            b1m = m1 * mag
            b2m = m2 * mag
            v1[0] -= dx * b2m
            v1[1] -= dy * b2m
            v1[2] -= dz * b2m
            v2[0] += dx * b1m
            v2[1] += dy * b1m
            v2[2] += dz * b1m
        for (r, [vx, vy, vz], m) in bodies:
            r[0] += dt * vx
            r[1] += dt * vy
            r[2] += dt * vz


def report_energy(bodies=SYSTEM, pairs=PAIRS, e=0.0):

    for (((x1, y1, z1), v1, m1),
         ((x2, y2, z2), v2, m2)) in pairs:
        dx = x1 - x2
        dy = y1 - y2
        dz = z1 - z2
        e -= (m1 * m2) / ((dx * dx + dy * dy + dz * dz) ** 0.5)
    for (r, [vx, vy, vz], m) in bodies:
        e += m * (vx * vx + vy * vy + vz * vz) / 2.
    print("%.9f" % e)


def offset_momentum(ref, bodies=SYSTEM, px=0.0, py=0.0, pz=0.0):

    for (r, [vx, vy, vz], m) in bodies:
        px -= vx * m
        py -= vy * m
        pz -= vz * m
    (r, v, m) = ref
    v[0] = px / m
    v[1] = py / m
    v[2] = pz / m


def main(n, ref='sun'):
    offset_momentum(BODIES[ref])
    report_energy()
    advance(0.01, n)
    report_energy()


if __name__ == '__main__':
    main(int(sys.argv[1]))
```

**Comment by tonybaloney** [comment]
Running a benchmark application once and once only will not give a fair result. 
Firstly, this includes the actual JIT-compilation time, so it will be slower, second, the compiler has a profiling optimizer so it won't be able to make optimisations that make the code faster if its only run once.

In your example, you have to set `pyjion.config(level=2)` to see some performance improvements.

Alternatively, you can just run the benchmark by running the `tests/benchmarks/suite.py` script in the repository. This will run the unmodified version of the nbody test 25 times (5 times, repeated 5 times) https://github.com/tonybaloney/Pyjion/blob/develop/main/Tests/benchmarks/bench_nbody.py

RE: "one-shot scripts". If the code is only run once, there are some small optimisations that Pyjion will make, but without running it multiple times, its unable to profile the code and assert what types are being used. Because of that, you're unlikely to see a performance benefit, and more likely a slowdown. This is generally true of any JIT compiler that it will be slower if you only run it once.

Pyjion does have a threshold setting so you can disable it for functions that are only run once.

**Comment by hanabi1224** [comment]
> but without running it multiple times, its unable to profile the code and assert what types are being used. 

I don't think that's the case, because the actual cost comes from function `advance` which runs N=50000 times in the 'one-shot' scenario. And I believe all toy programs from benchmark games are designed with that in mind to trivialize JIT compilation time in a 'one-shot' run

If we compare pypy3 with and without JIT, you can see JIT brings ~13X performance boost in 'one-shot' scenario

![image](https://user-images.githubusercontent.com/6546635/142709740-3b1dfc1b-c541-4d7a-9b69-0063d4fce1b6.png)

**Comment by tonybaloney** [comment]
The N value in the algorithm is the length of the range, not the time the function is called. 

I gave a talk about the nbody algorithm and why CPython is slow to execute it at PyCon a couple of years ago https://youtu.be/I4nkgJdVZFA

PyPy executes advance faster natively because it's floating point number implementation uses unboxed stack values instead of heap allocated values. 

Because Pyjion is a JIT for CPython, it is compatible with the Cpython C-API, which uses heap allocated objects for simple numeric types. Pyjion uses CPython's C-API in naive compilation. Pyjion looks for opportunities to replace floating point and 64-bit integers with stack values and rewrites the JITed code in the second iteration, this is called PGC. If you run the benchmark twice, as is done in the benchmark suite, the slowest part of the advance function is compiled into a more efficient version that doesn't use PyFloatObject.

**Comment by hanabi1224** [comment]
> The N value in the algorithm is the length of the range, not the time the function is called.

My bad, I did not read the python code carefully, but in most of the nbody implementations in other languages (especially for those who have JIT compilers), advance is called N times, so looks like this python version is specially deoptimized for JIT.

I made a version base on [go implementation](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-go-2.html) and here's the result

The new version is much slower in CPython but much faster in pypy
![image](https://user-images.githubusercontent.com/6546635/142720760-7fbd9d4b-0716-4335-a0a7-473237432b0e.png)

The new version with Pyjion is also much faster than old version, and a little faster than CPython
![image](https://user-images.githubusercontent.com/6546635/142720788-b7ee65bb-5cd4-48c2-9719-832673fce6c0.png)

When I run the new version in microbenchmark, time difference between the 1st run (actually the mean of 1st batch) and subsequent runs are less obvious
![image](https://user-images.githubusercontent.com/6546635/142720952-987f035c-5859-40d3-8d4a-e2d317a4f41b.png)


```python
import sys, math


class Body(object):
    def __init__(self, p, v, m):
        (self.x, self.y, self.z) = p
        (self.vx, self.vy, self.vz) = v
        self.m = m

PI = 3.14159265358979323
SOLAR_MASS = 4 * PI * PI
DAYS_PER_YEAR = 365.24
BODIES = {
    'sun': Body([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], SOLAR_MASS),

    'jupiter': Body([4.84143144246472090e+00,
                 -1.16032004402742839e+00,
                 -1.03622044471123109e-01],
                [1.66007664274403694e-03 * DAYS_PER_YEAR,
                 7.69901118419740425e-03 * DAYS_PER_YEAR,
                 -6.90460016972063023e-05 * DAYS_PER_YEAR],
                9.54791938424326609e-04 * SOLAR_MASS),

    'saturn': Body([8.34336671824457987e+00,
                4.12479856412430479e+00,
                -4.03523417114321381e-01],
               [-2.76742510726862411e-03 * DAYS_PER_YEAR,
                4.99852801234917238e-03 * DAYS_PER_YEAR,
                2.30417297573763929e-05 * DAYS_PER_YEAR],
               2.85885980666130812e-04 * SOLAR_MASS),

    'uranus': Body([1.28943695621391310e+01,
                -1.51111514016986312e+01,
                -2.23307578892655734e-01],
               [2.96460137564761618e-03 * DAYS_PER_YEAR,
                2.37847173959480950e-03 * DAYS_PER_YEAR,
                -2.96589568540237556e-05 * DAYS_PER_YEAR],
               4.36624404335156298e-05 * SOLAR_MASS),

    'neptune': Body([1.53796971148509165e+01,
                 -2.59193146099879641e+01,
                 1.79258772950371181e-01],
                [2.68067772490389322e-03 * DAYS_PER_YEAR,
                 1.62824170038242295e-03 * DAYS_PER_YEAR,
                 -9.51592254519715870e-05 * DAYS_PER_YEAR],
                5.15138902046611451e-05 * SOLAR_MASS)}

SYSTEM = list(BODIES.values())
N_BODIES = len(SYSTEM)


def advance(dt, bodies=SYSTEM):
    for i in range(N_BODIES):
        b1 = bodies[i]
        for j in range(i+1, N_BODIES):
            b2 =bodies[j]
            dx = b1.x - b2.x
            dy = b1.y - b2.y
            dz = b1.z - b2.z

            d_squared = dx*dx + dy*dy + dz*dz
            distance = math.sqrt(d_squared)

            mag = dt / (d_squared * distance)

            m2_multi_mag = b2.m * mag
            b1.vx -= dx * m2_multi_mag
            b1.vy -= dy * m2_multi_mag
            b1.vz -= dz * m2_multi_mag

            m1_multi_mag = b1.m * mag
            b2.vx += dx * m1_multi_mag
            b2.vy += dy * m1_multi_mag
            b2.vz += dz * m1_multi_mag

    for b in bodies:
        b.x += dt * b.vx
        b.y += dt * b.vy
        b.z += dt * b.vz


def report_energy(bodies=SYSTEM, e=0.0):
    for i in range(N_BODIES):
        b1 = bodies[i]
        e += 0.5 * b1.m * (b1.vx * b1.vx + b1.vy * b1.vy + b1.vz * b1.vz)
        for j in range(i + 1, N_BODIES):
            b2 =bodies[j]
            dx = b1.x - b2.x
            dy = b1.y - b2.y
            dz = b1.z - b2.z
            distance = math.sqrt(dx*dx + dy*dy + dz*dz)
            e -= b1.m * b2.m / distance
    print("%.9f" % e)


def offset_momentum(ref, bodies=SYSTEM, px=0.0, py=0.0, pz=0.0):
    for b in bodies:
        px -= b.vx * b.m
        py -= b.vy * b.m
        pz -= b.vz * b.m
    ref.vx = px / SOLAR_MASS
    ref.vy = py / SOLAR_MASS
    ref.vz = pz / SOLAR_MASS

def main(n, ref='sun'):
    offset_momentum(BODIES[ref])
    report_energy()
    for i in range(n):
        advance(0.01)
    report_energy()


if __name__ == '__main__':
    main(int(sys.argv[1]))
```
