### ISSUE TITLE
Error: disassembly only supported on x86_64

### ISSUE THREAD

**Issue by hez2010** [tonybaloney/Pyjion#483]
https://github.com/tonybaloney/Pyjion/blob/95f65c515d4252f5c58709dc95b7c587366d1113/src/pyjion/dis.py#L624

`machine()` may also return `AMD64` instead of `x86_64`.

**Comment by tonybaloney** [comment]
What OS, version and architecture are you on to see this value?

**Comment by hez2010** [comment]
Windows 11 x64

**Comment by tonybaloney** [comment]
Thanks. Just checked on a test machine and can reproduce.
