### ISSUE TITLE
Use pyperformance to test the performance of pyjion，SURPRISE!!!

### ISSUE THREAD

**Issue by zhuofeng6** [tonybaloney/Pyjion#488]
i install pyjion, and use pyperformance to test
`pyperformance run -p=/usr/local/python3.10/bin/pyjion -o py-jit.json`
then i use pyperformance to test with python3.10
`pyperformance run -p=/usr/local/python3.10/bin/python3.10 -o py310.json`
i found, It has no performance boost at all, why????
![image](https://user-images.githubusercontent.com/67537842/170484877-038ccb15-04db-4797-bd34-bcbdadc34cc4.png)

**Comment by tonybaloney** [comment]
If the numbers are 1.0x, then it's definitely not running Pyjion. (it would be slower or faster)

I've never tried running the Pyperformance benchmark suite in that way, I don't think it would work because of how it invokes Python interpreters.

**Comment by zhuofeng6** [comment]
In this case, what should be used to test the performance of pyjion?

**Comment by tonybaloney** [comment]
There is a benchmark suite script in the source repo, it gets run on CI

https://github.com/tonybaloney/Pyjion/runs/5967372554?check_suite_focus=true

See https://github.com/tonybaloney/Pyjion/blob/develop/main/Tests/benchmarks/suite.py

`python Tests/benchmarks/suite.py`

If you want to add another benchmark you can to the folder in tests, e.g. `bench_example` by adding a `__benchmarks__` list to the bottom of the file.

`python Tests/benchmarks/suite.py example`

There are some existing benchmarks from the pyperformance suite already in the folder (e.g. delta blue, fannkuch, n-body).

**Comment by zhuofeng6** [comment]
This is only using the performance of pyjion.

![image](https://user-images.githubusercontent.com/67537842/170668380-bd39ff1e-225b-48ab-85a8-0fb7de03bcf2.png)

How do compare performance with pyjion and without pyjion in python using ` a benchmark suite script in the source repo`

**Comment by tonybaloney** [comment]
> This is only using the performance of pyjion.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/67537842/170668380-bd39ff1e-225b-48ab-85a8-0fb7de03bcf2.png)
> 
> 
> 
> How do compare performance with pyjion and without pyjion in python using ` a benchmark suite script in the source repo`
> 
> 

It runs each benchmark twice. Once without Pyjion and once with Pyjion. The number without is the numbers in purple. 
The right 3 columns show the percentage difference between the two

**Comment by zhuofeng6** [comment]
WHAT! it is surprised me so much!

So the performance of using pyjion may be reduced?

**Comment by tonybaloney** [comment]
> WHAT! it is surprised me so much!
> 
> 
> 
> So the performance of using pyjion may be reduced? 

Yes. Some benchmarks are faster and some are slower.
