### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by Ehco1996** [tonybaloney/Pyjion#8]
hi, i am glad to see this project alive again,and eager to test it

but when i install python 3.9.0 through pyenv and pip install pyjion my scripts run failed

error log here:

```
Traceback (most recent call last):
  File "/Users/ehco/Documents/code/aioshadowsocks/test.py", line 1, in <module>
    import pyjion
  File "/Users/ehco/.pyenv/versions/3.9.0/envs/aio3/lib/python3.9/site-packages/pyjion/__init__.py", line 60, in <module>
    from ._pyjion import *  # NOQA
ImportError: dlopen(/Users/ehco/.pyenv/versions/3.9.0/envs/aio3/lib/python3.9/site-packages/pyjion/_pyjion.cpython-39-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Users/ehco/.pyenv/versions/3.9.0/envs/aio3/lib/python3.9/site-packages/pyjion/_pyjion.cpython-39-darwin.so
  Reason: image not found
```

can you give me some advice?

thanks

**Comment by tonybaloney** [comment]
What OS/distribution are you on?

What commands did you use to install the package?

**Comment by Ehco1996** [comment]
@tonybaloney 

* Mac os 10.15
* pyenv install 3.9.0 && pip install pyjion

i just open python shell and click this 
`` `
import pyjion
pyjion.enable()
```

**Comment by tonybaloney** [comment]
I think this is related to #9 (which is fixed and will be released in 0.0.3)

**Comment by tonybaloney** [comment]
Try version 0.0.3 that I just released on PyPi and see if this fixes your issue

**Comment by Ehco1996** [comment]
@tonybaloney  thanks  i upgrade to 0.0.3 everything is ok
