### ISSUE TITLE
imoprt failed on macOS

### ISSUE THREAD

**Issue by aisk** [tonybaloney/Pyjion#93]
Python version: 3.9.1
macOS version: 11.0.1 (Big Sur)

Install pyjion by pip: `$ pip install pyjion`, and after a long wait the build is finished with logs:

```
❯ pip install pyjion
Looking in indexes: https://-----------/simple/
Collecting pyjion
  Downloading https://-----------/pkg/pypi/pyjion/pyjion-0.3.0.tar.gz
     \ 104 kB 646 kB/s
  Installing build dependencies ... /
done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pyjion
  Building wheel for pyjion (PEP 517) ... done
"~/Codes/pylibs/-----------/venv/lib/python3.9/site-packages/pyjion/__init__.py" 67L, 2306B
  Created wheel for pyjion: filename=pyjion-0.3.0-py3-none-any.whl size=14374 sha256=2e8f9b7f8e17c7895246c256cd73ad21309df26731a57fad3da460e7f0869420
  Stored in directory: /Users/-----------/Library/Caches/pip/wheels/db/9f/c4/e64aa2f612b99de7ac91c06864a410865865151b85ae631bb1
"~/Codes/pylibs/-----------/venv/lib/python3.9/site-packages/pyjion/wsgi.py" 11L, 307B
Successfully built pyjion
Installing collected packages: pyjion
Successfully installed pyjion-0.3.0
```

And failed to using it:

```
❯ python3
Python 3.9.1 (default, Dec 20 2020, 11:38:32)
[Clang 12.0.0 (clang-1200.0.31.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyjion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/-----------/Codes/pylibs/-----------/venv/lib/python3.9/site-packages/pyjion/__init__.py", line 67, in <module>
    from ._pyjion import *  # NOQA
ModuleNotFoundError: No module named 'pyjion._pyjion'
>>>
```

And found there is no `_pyjion` module:

```
❯ ls venv/lib/python3.9/site-packages/pyjion/
__init__.py  __pycache__/ dis.py       wsgi.py
```

**Comment by tonybaloney** [comment]
This means the C package failed to compile. What sort of Mac is this?

**Comment by aisk** [comment]
MacBook Pro (16-inch, 2019), with X86 processor.

> This means the C package failed to compile.

I think exit the install process with non 0 status code is a good behavior for users can found the issue in building process.

**Comment by tonybaloney** [comment]
I assumed you were running an M1. 
If its a regular Mac pip should return an error if it failed to install correctly.

Could you uninstall the package and reinstall with pip's verbose mode (`-v`) please

**Comment by tonybaloney** [comment]
@aisk can you try updating to 0.5.0? I noticed the wheel for macOS 11 is missing from the 0.4.0 release package

**Comment by aisk** [comment]
0.5.0 got build very fast, and I think it's not as expected. and the _pyjion module dose not exist as above. I'll get the detail on weekend.

**Comment by aisk** [comment]
And sorry I'm using a intel CPU mac.

**Comment by aisk** [comment]
Full build log here:
[pip.log.tar.gz](https://github.com/tonybaloney/Pyjion/files/5753095/pip.log.tar.gz)

**Comment by tonybaloney** [comment]
Managed to reproduce this locally. This is due to a bug in pip. Please upgrade to 20.3 and try installing again, it will install the correct wheel.

**Comment by aisk** [comment]
Yes the wheel format is installed correctly, but install it with `pip install --no-binary pyjion pyjion` have the same issue. But for my case, I will use the wheel format for next steps for tests, really thanks!
